#!/bin/sh

out=rs232_c.c

rates=$(cat <<EOF
0
50
75
110
134
150
200
300
600
1200
1800
2400
4800
7200
9600
14400
19200
28800
38400
57600
76800
115200
230400
460800 
500000 
576000 
921600 
1000000
1152000
1500000
2000000
2500000
3000000
3500000
4000000
EOF)

cat > $out <<EOF
#include <sys/types.h>
#include <stdlib.h>
#include <fcntl.h>
#include <termios.h>

#include "_cgo_export.h"

/*
  This is automatically generated by genc.sh
*/

void initBaudRates() {
EOF

for r in $rates
do
    echo "#ifdef B$r" >> $out
    echo "    addBaudRate($r, B$r);" >> $out
    echo "#endif" >> $out
done

echo "}" >> $out
