#include <sys/types.h>
#include <stdlib.h>
#include <fcntl.h>
#include <termios.h>

#include "_cgo_export.h"

/*
  This is automatically generated by genc.sh
*/

void initBaudRates() {
#ifdef B0
    addBaudRate(0, B0);
#endif
#ifdef B50
    addBaudRate(50, B50);
#endif
#ifdef B75
    addBaudRate(75, B75);
#endif
#ifdef B110
    addBaudRate(110, B110);
#endif
#ifdef B134
    addBaudRate(134, B134);
#endif
#ifdef B150
    addBaudRate(150, B150);
#endif
#ifdef B200
    addBaudRate(200, B200);
#endif
#ifdef B300
    addBaudRate(300, B300);
#endif
#ifdef B600
    addBaudRate(600, B600);
#endif
#ifdef B1200
    addBaudRate(1200, B1200);
#endif
#ifdef B1800
    addBaudRate(1800, B1800);
#endif
#ifdef B2400
    addBaudRate(2400, B2400);
#endif
#ifdef B4800
    addBaudRate(4800, B4800);
#endif
#ifdef B7200
    addBaudRate(7200, B7200);
#endif
#ifdef B9600
    addBaudRate(9600, B9600);
#endif
#ifdef B14400
    addBaudRate(14400, B14400);
#endif
#ifdef B19200
    addBaudRate(19200, B19200);
#endif
#ifdef B28800
    addBaudRate(28800, B28800);
#endif
#ifdef B38400
    addBaudRate(38400, B38400);
#endif
#ifdef B57600
    addBaudRate(57600, B57600);
#endif
#ifdef B76800
    addBaudRate(76800, B76800);
#endif
#ifdef B115200
    addBaudRate(115200, B115200);
#endif
#ifdef B230400
    addBaudRate(230400, B230400);
#endif
#ifdef B460800
    addBaudRate(460800, B460800);
#endif
#ifdef B500000
    addBaudRate(500000, B500000);
#endif
#ifdef B576000
    addBaudRate(576000, B576000);
#endif
#ifdef B921600
    addBaudRate(921600, B921600);
#endif
#ifdef B1000000
    addBaudRate(1000000, B1000000);
#endif
#ifdef B1152000
    addBaudRate(1152000, B1152000);
#endif
#ifdef B1500000
    addBaudRate(1500000, B1500000);
#endif
#ifdef B2000000
    addBaudRate(2000000, B2000000);
#endif
#ifdef B2500000
    addBaudRate(2500000, B2500000);
#endif
#ifdef B3000000
    addBaudRate(3000000, B3000000);
#endif
#ifdef B3500000
    addBaudRate(3500000, B3500000);
#endif
#ifdef B4000000
    addBaudRate(4000000, B4000000);
#endif
}
